### ISSUE TITLE
[FEATURE] Set SELinux state to permissive

### ISSUE THREAD

**Issue by thedatabaseme** [thedatabaseme/pythia#27]
**Is your feature request related to a problem? Please describe.**
Pythia doesn't check if SELinux is set to `enforcing`. If so, for instance, the autostart feature of Oracle will not work with following message in the /var/log/messages:

```
SELinux is preventing dbstart from create access on the file ORA21_lgwr_2085.trc.#012#012*****  Plugin catchall_labels (83.8 confidence) suggests   *******************#012#012If you want to allow dbstart to have create access
```

**Describe the solution you'd like**
Pythia should check in the prerequisites (at least for enabling autostart) that SELinux is set to `permissive`. This can be done with the module `selinux` which is in the collection `ansible.posix`.

Example:
```
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive
```

**Additional context**
Most likely a reboot is required when setting SELinux to permissive. 

- [x] Merged in develop branch
- [x] Merged in master branch
