### ISSUE TITLE
[FEATURE] Linting should be done by more current ansible-lint

### ISSUE THREAD

**Issue by thedatabaseme** [thedatabaseme/pythia#44]
**Is your feature request related to a problem? Please describe.**
We're using ansible-lint Github Action module in an old version. The reason for this is, that a more current reason doesn't offer the options we need anymore.

**Describe the solution you'd like**
We should do the linting with ansible-lint by ourself instead rely on the Github action module.

**Additional context**
This could be done like this:

```
---
name: Lint
'on':
  pull_request:
  push:
    branches:
      - master

jobs:

  test:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.7.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint ansible

      - name: Run yamllint.
        run: yamllint .

      - name: Run ansible-lint.
        run: ansible-lint . -x command-instead-of-shell -x risky-shell-pipe -x no-jinja-when -x fqcn-builtins

```
